### ISSUE TITLE
Velodyne Driver Version 

### ISSUE THREAD

**Issue by nisailhan** [tier4/AutowareArchitectureProposal_launcher#105]
```
find_package(velodyne_driver 0.2.0 EXACT REQUIRED)
find_package(velodyne_pointcloud 0.2.0 EXACT REQUIRED)
```
CMakeLists.txt of sensing_launch folder wants the above versions of velodyne drivers. However, when I checked these versions, i saw that there were versions released in 2010. Support is no longer available. Latest version: 2.1.0
I modified these versions in CMake file for successful completion of compile. Does it cause problems?

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

It's a hacky method for enforcing the velodyne_driver's version to be our customized version, so it's not recommended to change that.
