### ISSUE TITLE
Considering system monitor param to split for each product 

### ISSUE THREAD

**Issue by taikitanaka3** [tier4/AutowareArchitectureProposal_launcher#162]
Currently ad_service_state_monitor in  system launch refers to .universe config file so it would be better to refer system launch's config file moving config file.
```
  <arg name="config_file" default="$(find-pkg-share ad_service_state_monitor)/config/ad_service_state_monitor.param.yaml" />
to
  <arg name="config_file" default="$(find-pkg-share ad_service_state_monitor)/config/config/ad_service_state_monitor.param.yaml" />
```

https://github.com/autowarefoundation/autoware.universe/tree/tier4/proposal/system/ad_service_state_monitor/config

or is there any better reason to refer to .universe config file?

**Comment by taikitanaka3** [comment]
close this issue 
to decide use default param (parameters in .universe package)as much as possible

**Comment by kenji-miyake** [comment]
>   <arg name="config_file" default="$(find-pkg-share ad_service_state_monitor)/config/config/ad_service_state_monitor.param.yaml" />

I'm sorry, I couldn't understand well...
Did you mean `$(find-pkg-share system_launch)/config/ad_service_state_monitor.param.yaml`?
