### ISSUE TITLE
We cannot change `lat_controller_param_path` in `control.launch.py` from outside in the form of launch arguments.

### ISSUE THREAD

**Issue by h-ohta** [tier4/AutowareArchitectureProposal_launcher#183]
https://github.com/tier4/autoware_launch/blob/42fca870919c036697d5e7400146823939fbca05/control_launch/launch/control.launch.py#L35-L49

Now, We cannot change `lat_controller_param_path` from outside in the form of launch arguments.

I'd like to set from launch arguments like followings.
``` 
<arg name="individual_params_config" default="$(find-pkg-share individual_params)/config/$(var vehicle_id)/"/>
<include file="$(find-pkg-share control_launch)/launch/control.launch.py">
    <arg name="lateral_controller_mode" value="pure_pursuit" />
    <arg name="lat_controller_param_path" value="$(var individual_params_config)/control_launch/pure_pursuit.param.yaml" />
</include>
```

**Comment by h-ohta** [comment]
I'm glad to that `lat_controller_param_path` is changed like below.
https://github.com/tier4/autoware_launch/blob/42fca870919c036697d5e7400146823939fbca05/control_launch/launch/control.launch.py#L319-L326

**Comment by h-ohta** [comment]
@rej55 Do you have any ideas? thank you for your cooperation.

**Comment by rej55** [comment]
I think it may achieve it if we define `pure_pursuit_param_path` and `mpc_follower_param_path` as the launch argument.
Then, we should change the following code to `lat_controller_param_path = LaunchConfiguration("mpc_follower_param_path").perform(context)`.

https://github.com/tier4/autoware_launch/blob/42fca870919c036697d5e7400146823939fbca05/control_launch/launch/control.launch.py#L37-L40

**Comment by kenji-miyake** [comment]
Actually, it is public.

**Comment by h-ohta** [comment]
@rej55 That sounds good. 
However, I think `pure_pursuit_param_path` and `mpc_follower_param_path` is redundant.
It seems enough that `lat_controller_param_path` is only defined.
For example, we can set `lat_controller_param_path` like below if we have parameter file names same as `lateral_controller_mode`.

```
<arg name="individual_params_config" default="$(find-pkg-share individual_params)/config/$(var vehicle_id)/"/>
<include file="$(find-pkg-share control_launch)/launch/control.launch.py">
    <arg name="lateral_controller_mode" value="mpc_follower" />
    <arg name="lat_controller_param_path" value="$(var individual_params_config)/control_launch/$(var lateral_controller_mode).param.yaml" />
</include>
```

**Comment by h-ohta** [comment]
I'll make pull request and let's discuss in it.
