### ISSUE TITLE
Porting Interpolate Nodelet

### ISSUE THREAD

**Issue by mitsudome-r** [tier4/AutowareArchitectureProposal_launcher#22]
I've been porting the interpolate nodelet from this repository for sensing_launch. https://github.com/tier4/velodyne_vls

However, there are other changes made to other nodelets in velodyne_pointcloud and velodyne_driver which interpolate nodelet depends on. (e.g. additional azimuth, timestamp fields added to sensor_msgs::PointCloud2 topic).
The repo has diverged from original https://github.com/ros-drivers/velodyne repo, and it is difficult to just add the nodelet to it's ros2 branch.

I'm currently doing the porting of https://github.com/tier4/velodyne_vls so that we can use it for testing it on the vehicle next week, but we probably should port this feature to the driver in Autoware.Auto repository rather than doing maintenance under Tier4 repository. Autoware.Auto driver also has better code quality as well.

**Comment by fred-apex-ai** [comment]
blocks #14
